name: Manual workflow

on:
 push:

env:
  PROJ_DIR: $GITHUB_WORKSPACE
jobs:
 build:
   runs-on: Windows

   steps:
     - uses: actions/checkout@v6

     - name: demo QA in CI
       run: echo "demo QA in CI - $PROJ_DIR - $GITHUB_WORKSPACE"
       run: vcast/setenv.bat && c:/dev/VCAST/2026sp1/vpython c:/dev/VCAST/vectorcast_gitlab/vc_scripts/vcast_exec.py vcast/Diner_Manager.vcm  --build-execute --ci --incremental 
   
         #- name: Get covergae
         #run: echo get coverage
         #- uses: 5monkeys/cobertura-action@master
         #with:
         #path: vcast/xml_data/cobertura/coverage_results_project.xml
         #minimum_coverage: 75
         #skip_covered: false
         #show_line: true
         #show_branch: true
         #report_name: VectorCAST Code Coverage
         #show_missing: true
